services:
  rio-console:
    build: .
    container_name: rio-console
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - type: bind
        source: ./data
        target: /run/rio-console
        read_only: true
    networks:
      - deepria-web

networks:
  deepria-web:
    external: true
